routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('mailable', function () {
    return ok([]);
});

Route::post('/aspirantes-listado-general', 'Reportes\AspiranteController@export')
    ->name('reporte.general.aspirnates');

Route::post('/listado-general-mslp', 'Reportes\AspiranteController@listadoGeneralSMLP')
    ->name('reporte.general.mslp');

Route::get('/prueba-stress', function () {
    $repo = new \Subsistema\Repositories\OfertaEducativaRepository();

    $json = $repo->catalogoOpcionesEducativas()->get();

    return ok(compact('json'));
});

Route::prefix('/developer-zone')
    ->name('developer.')
    ->middleware([ 'auth', 'role:supermario' ])
    ->group(function () {
        Route::get('/services', 'Developer\ServicesController@index')->name('services');
    });

Route::get('/reset-password/faker', function () {
    $user  = \ExamenEducacionMedia\User::where('email', 'andresjch2804@gmail.com')->firstOrFail();
    $token = str_random(60);

    return new \ExamenEducacionMedia\Mail\ResetPasswordMail($user, $token);
});

Route::get('/olvide-contrasena', 'ResetPasswordController@index')->name('forgot.password');
Route::post('/olvide-contrasena', 'ResetPasswordController@store')->name('forgot.password');

Route::get('/restablecer-contrasena/{token}', 'ResetPasswordController@showResetForm')->name('reset.password');
Route::post('/update-password', 'ResetPasswordController@resetPassword')->name('cambiar.contrasena');

Route::prefix('/reportes')
    ->middleware([ 'auth', 'role:departamento|subsistema|plantel' ])
    ->name('reportes.')
    ->group(function () {
        Route::post('/oferta', 'ReporteController@oferta')->name('oferta');
        Route::get('/', 'ReporteController@index')->name('index');
    });

Route::view('/perfil', 'profile')
    ->middleware([ 'auth' ]);

Route::view('/aviso-privacidad', 'aviso_privacidad')->name('aviso.privacidad');

Route::post('/login-as-user', 'Auth\LoginAsController@loginAsUser')
    ->middleware([ 'auth', 'role:departamento' ])
    ->name('login.as.user');

Route::post('/logout-as-user', 'Auth\LoginAsController@logout')
    ->middleware([ 'auth' ])
    ->name('logout.as.user');

/*Route::middleware([ 'auth', 'role:departamento' ])
    ->prefix('/administracion')
    ->as('administracion.')
    ->group(function () {
        Route::view('/', 'administracion.home')->name('home');

        Route::prefix('/planteles')
            ->as('planteles.')
            ->group(function () {
                Route::view('/{all?}', 'administracion.planteles.home')
                    ->where([ 'all' => '.*' ])
                    ->name('spa');
            });
    });*/

Route::middleware([ 'auth', 'role:plantel|subsistema|aspirante' ])
    ->prefix('/')
    ->name('centro-descarga.')
    ->group(function () {
        Route::get('/documentos', 'CentroDescargaController@index')->name('cdescarga.index');
        Route::get('/descargar/{id}', 'CentroDescargaController@descargar')->name('descargar.doc');
    });


/*Route::view('/home', 'home')->middleware([ 'auth' ]);*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

/*Route::get('/registro', function () {
    return view('welcome');
})->middleware([ 'isRegistro' ]);

Route::get('/subsistema/aforo', function () {
    return view('welcome');
})->middleware([ 'isAforo' ]);

Route::get('/subsistema/oferta', function () {
    return view('subsistemas.home');
})->middleware([ 'isOferta' ]);*/


Route::group([ 'prefix' => '/planteles', 'middleware' => [ 'auth', 'role:plantel', 'hasPlantel' ] ], function () {
    Route::get('/', function () {
        return view('welcome');
    });
});

/* Login con jarvis*/
Route::get('/loging/oauth', 'Auth\LoginController@redirectToProvider')->name('login.oauth');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback')->name('login.oauth.callback');

Route::get('login/oauth-password', 'Auth\LoginJarvisController@showLoginForm')->name('login.jarvis');
Route::post('login/oauth-password', 'Auth\LoginJarvisController@login')->name('login.jarvis');
/*Login con jarvis*/

Auth::routes($options = [ 'register' => false, 'reset' => false ]);

Route::view('/cambiar-contrasena', 'update_password.index')
    ->middleware([ 'auth' ])
    ->name('update.password');
Route::patch('/cambiar-contrasena', 'UpdatePasswordController@update')
    ->middleware([ 'auth' ])
    ->name('update.password');

resources/views/centro_de_descargas/centro_descarga.blade.php
@extends((( $name_role->name == 'aspirante') ? 'aspirante.layouts.aspirante' : 'layouts.app' ))
@section('extra-head')
	<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
@endsection

@section('content')

	<div class="row justify-content-center">
		<div class="card card-primary card-outline col-md-7 mt-5 col-md-9">
			<div class="card-header">
				<h1 class="card-title">Centro de descargas</h1>
			</div>
			<div class="card-body text-center pb-0">
				<div class="table-responsive-sm">
					<table class="table table-bordered table-striped table-hover" id="filtro">
						<thead>
							<tr>
								<th>#</th>
								<th>Nombre del archivo</th>
								<th>Descripción</th>
								<th>Descargar</th>
							</tr>
						</thead>
						<tbody>
							@if(!empty($documentos))
								@foreach($documentos as $doc)
									<tr>
										<td>{{ $loop->iteration }}</td>
										<td>{{ $doc->archivo->nombre }}</td>
										<td>{{ $doc->archivo->descripcion }}</td>
										<td>
											<a class="btn btn-primary font-weight-light" href="{{route('centro-descarga.descargar.doc',$doc->archivo->id) }}">
												<i class="fa fa-download"> </i>
												Descargar</a>
										</td>
									</tr>
								@endforeach
						</tbody>
						@else
							<tr>
								<td colspan="8">No hay registros.</td>
							</tr>
						@endif
					</table>
				</div>
			</div>
		</div>
	</div>
	
@endsection
@section('extra-scripts')
	<script src="{{ asset('datatables/datatables.js') }}"></script>
	<script>
        $('#filtro').DataTable();
	</script>
@endsection

resources/views/centro_de_descargas/centro_descarga_aspirantes.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="csrf-token" content="{{ csrf_token() }}">
		<title>SIEM</title>
		<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
		@auth
			<meta name="api-token" content="{{ Auth::user()->api_token }}">
			<meta name="token" content="{{ Auth::user()->jarvis_user_access_token }}">
		@endauth

		<title>{{ config('app.name', 'Laravel') }}</title>
		@yield('extra-head')

		<link rel="stylesheet" href="{{ mix('css/adminlte.css') }}">
		@yield('extra-css')
		<style>
			body {
				height: 100vh !important;
			}
		</style>
	</head>
	<body>
		@include('partials.logos_banner')
		<div class="bg-primary">
			<div class="container py-4">
				<div class="d-sm-flex justify-content-sm-between align-items-sm-center">
					<div class="mb-3 mb-sm-0">
						<h5 class="mb-0">{{ get_user_full_name() }} <br> Folio
							CENEVAL: {{ get_aspirante()->folio }}<br></h5>
					</div>
					<a href="{{ route('aspirante.dashboard.index') }}"
					   class="btn bg-white" style="color: #1f2d3d!important">
						Regresar
					</a>
				</div>

			</div>

		</div>
		@yield('content')
		@routes
		<script src="{{ mix('js/adminlte.js') }}"></script>
		<script type="text/javascript">
            window.clone = function (obj) {
                return JSON.parse(JSON.stringify(obj));
            }
		</script>
		@yield('extra-scripts')
	</body>
</html>